#!/usr/bin/env bash
set -euo pipefail

die() { printf 'kvmcp setup: %s\n' "$*" >&2; exit 1; }

[[ $EUID -ne 0 ]] || die 'Run as the account that will run kvmcp, without sudo.'
command -v sudo >/dev/null || die 'sudo is required to install systemd services.'
command -v systemctl >/dev/null || die 'systemd is required.'

script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)
project_dir=$(cd -- "$script_dir/.." && pwd -P)
run_user=$(id -un)
[[ $project_dir =~ ^/[[:alnum:]_./-]+$ ]] || die 'Project path contains characters unsupported by this service installer; move it to a simple absolute path.'
[[ -x $project_dir/.venv/bin/kvmcp ]] || die 'Run uv sync in the project directory first.'
[[ -f $project_dir/config.toml ]] || die 'config.toml is missing.'
vid=${KVMCP_USB_VID:?Set KVMCP_USB_VID to the USB vendor ID}
pid=${KVMCP_USB_PID:?Set KVMCP_USB_PID to the USB product ID}
mouse_mode=${KVMCP_MOUSE_MODE:-absolute}

hid_unit=/etc/systemd/system/kvmcp-hid.service
server_unit=/etc/systemd/system/kvmcp.service
for unit in "$hid_unit" "$server_unit"; do
    if sudo test -e "$unit" && ! sudo grep -q '^# Generated by kvmcp setup-kvmcp.sh$' "$unit"; then
        die "$unit already exists and was not created by this script; leaving it untouched."
    fi
done

sudo env KVMCP_USB_VID="$vid" KVMCP_USB_PID="$pid" KVMCP_MOUSE_MODE="$mouse_mode" \
    /bin/bash "$script_dir/setup-hid-gadget.sh"

tmp_dir=$(mktemp -d)
cleanup() {
    rm -f -- "$tmp_dir/kvmcp-hid.service" "$tmp_dir/kvmcp.service"
    rmdir -- "$tmp_dir"
}
trap cleanup EXIT

cat > "$tmp_dir/kvmcp-hid.service" <<EOF
# Generated by kvmcp setup-kvmcp.sh
[Unit]
Description=kvmcp USB HID Gadget
After=systemd-udev-trigger.service
StartLimitIntervalSec=0

[Service]
Type=oneshot
RemainAfterExit=yes
Environment=KVMCP_USB_VID=$vid
Environment=KVMCP_USB_PID=$pid
Environment=KVMCP_MOUSE_MODE=$mouse_mode
ExecStart=/bin/bash $script_dir/setup-hid-gadget.sh
Restart=on-failure
RestartSec=3

[Install]
WantedBy=multi-user.target
EOF

cat > "$tmp_dir/kvmcp.service" <<EOF
# Generated by kvmcp setup-kvmcp.sh
[Unit]
Description=kvmcp MCP server
Wants=kvmcp-hid.service
After=network.target kvmcp-hid.service

[Service]
Type=simple
User=$run_user
SupplementaryGroups=video
WorkingDirectory=$project_dir
ExecStart=$project_dir/.venv/bin/kvmcp -c $project_dir/config.toml
Restart=on-failure
RestartSec=3

[Install]
WantedBy=multi-user.target
EOF

sudo install -m 0644 "$tmp_dir/kvmcp-hid.service" "$hid_unit"
sudo install -m 0644 "$tmp_dir/kvmcp.service" "$server_unit"
sudo systemctl daemon-reload
sudo systemctl enable kvmcp-hid.service kvmcp.service
sudo systemctl restart kvmcp-hid.service
sudo systemctl restart kvmcp.service
printf 'Installed and started kvmcp for %s from %s (HID %s:%s, %s mouse).\n' "$run_user" "$project_dir" "$vid" "$pid" "$mouse_mode"
printf 'Check status with: systemctl status kvmcp-hid kvmcp\n'
